version: "3.7"

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=prod
    ports:
      - "23456:23456"
    volumes:
      - .:/usr/src/app
    networks:
      - app-network
    command: node index.js

networks:
  app-network:
    driver: bridge
